/**
 * Implementation of the Simplex Method 
 * @version 0.9.1
 * @author José Alfredo Brambila Hernández <alfredo.brambila@outlook.com>
 * 
 * SOFTWARE LICENCE
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
 * and associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, 
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is 
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
 * BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * 
 */

package gui;

import domain.GUILoader;
import domain.SimplexTable;
import java.awt.Desktop;
import java.awt.GridBagConstraints;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.io.File;
import java.io.IOException;

/**
 *
 * @author al_x3
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    
    private SimplexTable simplexModel;
    GUILoader guiLoader = new GUILoader();
    
    private JTextField[] f;
    private JTextField[] z;
    private JComboBox[] combo;
    private double [][] matriz;
    private double [][] array;
    private double [] vectorZ;
    private double [] vectorD;
    private String[] desigualdades;
    private String[][] tablaSimplex;
    boolean maximizar;
    
    private int nVars;
    private int nRest;
    
    
    
    public JFramePrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNVars = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNRest = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonResolver = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBoxObjetivo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonTBDesdeArchivo = new javax.swing.JButton();
        jButtonTBResolver = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemCargaDesdeArchivo = new javax.swing.JMenuItem();
        jMenuItemResolver = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Método Simplex");
        setPreferredSize(new java.awt.Dimension(950, 680));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Método SIMPLEX");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Variables y Restricciones"));

        jLabel1.setText("Número de Variables:");

        jTextFieldNVars.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNVarsFocusLost(evt);
            }
        });
        jTextFieldNVars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNVarsActionPerformed(evt);
            }
        });
        jTextFieldNVars.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNVarsKeyPressed(evt);
            }
        });

        jLabel2.setText("Número de restricciones:");

        jTextFieldNRest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNRestFocusLost(evt);
            }
        });
        jTextFieldNRest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNRestKeyPressed(evt);
            }
        });

        jButton1.setText("Aplicar");
        jButton1.setToolTipText("Aplicar valores y ver formulario de captura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNVars, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNRest, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNVars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Botones"));

        jButtonResolver.setBackground(new java.awt.Color(0, 204, 255));
        jButtonResolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support/icos/verificacion_16.png"))); // NOI18N
        jButtonResolver.setText("Resolver");
        jButtonResolver.setToolTipText("Resolver con Simplex");
        jButtonResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResolverActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support/icos/cerrar_16.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.setToolTipText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBoxObjetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maximizar", "Minimizar" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("¿Objetivo de la función?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResolver)
                    .addComponent(jButton3)
                    .addComponent(jComboBoxObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        jButtonTBDesdeArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support/icos/carpeta_24.png"))); // NOI18N
        jButtonTBDesdeArchivo.setToolTipText("Cargar instancia desde archivo");
        jButtonTBDesdeArchivo.setFocusable(false);
        jButtonTBDesdeArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTBDesdeArchivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTBDesdeArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTBDesdeArchivoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonTBDesdeArchivo);

        jButtonTBResolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support/icos/verificacion_24.png"))); // NOI18N
        jButtonTBResolver.setToolTipText("Resolver con Simplex");
        jButtonTBResolver.setFocusable(false);
        jButtonTBResolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTBResolver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTBResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTBResolverActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonTBResolver);

        jMenu1.setText("Archivo");
        jMenu1.add(jSeparator1);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Proceso");

        jMenuItemCargaDesdeArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support/icos/carpeta_16.png"))); // NOI18N
        jMenuItemCargaDesdeArchivo.setText("Cargar desde archivo");
        jMenuItemCargaDesdeArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargaDesdeArchivoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCargaDesdeArchivo);

        jMenuItemResolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support/icos/verificacion_16.png"))); // NOI18N
        jMenuItemResolver.setText("Resolver");
        jMenuItemResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResolverActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemResolver);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ayuda");

        jMenuItem4.setText("Ayuda");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator2);

        jMenuItem5.setText("Acerca de...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNVarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNVarsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldNVarsActionPerformed

    private void jButtonResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolverActionPerformed
        // TODO add your handling code here:
        //System.out.println(this.jComboBox1.getSelectedIndex());
        if(this.jTextFieldNVars.getText().isEmpty() || this.jTextFieldNRest.getText().isEmpty() || this.combosVacios()) {
            JOptionPane.showMessageDialog(null, "Debe intruducir valores al modelo", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            retornaMatriz(Integer.parseInt(this.jTextFieldNRest.getText()), Integer.parseInt(this.jTextFieldNVars.getText()));
            JFrameTablaSimplex simplex = new JFrameTablaSimplex(guiLoader);
            //
            simplex.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println("WindowClosingDemo.windowClosing");
                //System.exit(0);
                JFramePrincipal frame = new JFramePrincipal();
                frame.setVisible(true);

            }
            });
            //
            simplex.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonResolverActionPerformed
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!this.jTextFieldNVars.getText().isEmpty() && !this.jTextFieldNRest.getText().isEmpty()) {
            llena(Integer.parseInt(this.jTextFieldNVars.getText()),Integer.parseInt(this.jTextFieldNRest.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos de número de variables y número de restricciones", "Campos vacios", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            File path = new File ("File/manual.pdf");
            Desktop.getDesktop().open(path);
       }catch (IOException ex) {
            ex.printStackTrace();
       }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JFrameAcercaDe frame = new JFrameAcercaDe();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItemCargaDesdeArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargaDesdeArchivoActionPerformed
        // TODO add your handling code here:
        JFrameDesdeArchivo frame = new JFrameDesdeArchivo();
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                //System.out.println("WindowClosingDemo.windowClosing");
                //System.exit(0);
                JFramePrincipal frame = new JFramePrincipal();
                frame.setVisible(true);

            }
            });
        frame.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jMenuItemCargaDesdeArchivoActionPerformed

    private void jButtonTBDesdeArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTBDesdeArchivoActionPerformed
        // TODO add your handling code here:
        JFrameDesdeArchivo frame = new JFrameDesdeArchivo();
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                //System.out.println("WindowClosingDemo.windowClosing");
                //System.exit(0);
                JFramePrincipal frame = new JFramePrincipal();
                frame.setVisible(true);

            }
            });
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonTBDesdeArchivoActionPerformed

    private void jButtonTBResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTBResolverActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldNVars.getText().isEmpty() || this.jTextFieldNRest.getText().isEmpty() || this.combosVacios()) {
            JOptionPane.showMessageDialog(null, "Debe intruducir valores al modelo", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            retornaMatriz(Integer.parseInt(this.jTextFieldNRest.getText()), Integer.parseInt(this.jTextFieldNVars.getText()));
            JFrameTablaSimplex simplex = new JFrameTablaSimplex(guiLoader);
            //
            simplex.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                //System.out.println("WindowClosingDemo.windowClosing");
                //System.exit(0);
                JFramePrincipal frame = new JFramePrincipal();
                frame.setVisible(true);

            }
            });
            //
            simplex.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonTBResolverActionPerformed

    private void jMenuItemResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResolverActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldNVars.getText().isEmpty() || this.jTextFieldNRest.getText().isEmpty() || this.combosVacios()) {
            JOptionPane.showMessageDialog(null, "Debe intruducir valores al modelo", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            retornaMatriz(Integer.parseInt(this.jTextFieldNRest.getText()), Integer.parseInt(this.jTextFieldNVars.getText()));
            JFrameTablaSimplex simplex = new JFrameTablaSimplex(guiLoader);
            //
            simplex.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                //System.out.println("WindowClosingDemo.windowClosing");
                //System.exit(0);
                JFramePrincipal frame = new JFramePrincipal();
                frame.setVisible(true);

            }
            });
            //
            simplex.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemResolverActionPerformed

    private void jTextFieldNVarsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNVarsFocusLost
        // TODO add your handling code here:
        if(!this.jTextFieldNRest.getText().isEmpty() && !this.jTextFieldNVars.getText().isEmpty()) {
            llena(Integer.parseInt(this.jTextFieldNVars.getText()),Integer.parseInt(this.jTextFieldNRest.getText()));
        }
    }//GEN-LAST:event_jTextFieldNVarsFocusLost

    private void jTextFieldNVarsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNVarsKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER) {
            llena(Integer.parseInt(this.jTextFieldNVars.getText()),Integer.parseInt(this.jTextFieldNRest.getText()));
            this.jTextFieldNVars.transferFocus();
        }
    }//GEN-LAST:event_jTextFieldNVarsKeyPressed

    private void jTextFieldNRestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNRestFocusLost
        // TODO add your handling code here:
        if(!this.jTextFieldNRest.getText().isEmpty() && !this.jTextFieldNVars.getText().isEmpty()) {
            llena(Integer.parseInt(this.jTextFieldNVars.getText()),Integer.parseInt(this.jTextFieldNRest.getText()));
        }
    }//GEN-LAST:event_jTextFieldNRestFocusLost

    private void jTextFieldNRestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNRestKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER) {
            llena(Integer.parseInt(this.jTextFieldNVars.getText()),Integer.parseInt(this.jTextFieldNRest.getText()));
            this.jTextFieldNRest.transferFocus();
        }
    }//GEN-LAST:event_jTextFieldNRestKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private boolean combosVacios() {
        boolean vacios = false;
        for(int i=0; i<z.length; i++) {
            if(z[i].getText().isEmpty()) {
                vacios = true;
                break;
            }
        }
        
        for(int i=0; i<f.length; i++) {
            if(f[i].getText().isEmpty()) {
                vacios = true;
                break;
            }
        }
        
        return vacios;
    }
    private void retornaMatriz(int nrest, int nvars) {
        
        int v=0; int r=0;
        int f=0; 
        int c=0;
        int ir=0;
        this.vectorD = new double[nrest];
        this.matriz = new double[nrest][nvars];
        this.nRest = nrest;
        this.nVars = nvars;
        
        for(int i=0; i<this.f.length; i++) {
            if(c>=nvars) {
                c=0;
                f++;
                this.vectorD[ir++] = Double.parseDouble(this.f[i].getText().toString());
            } else {
                matriz[f][c++] = Double.parseDouble(this.f[i].getText().toString());
            }

            
        }
        
        this.vectorZ = new double[nvars];
        for(int i=0; i<this.z.length; i++) {
            this.vectorZ[i] = Double.parseDouble(this.z[i].getText().toString());
        }
        
        //Z
        //System.out.print("[ ");
        //for(int i=0; i<this.vectorZ.length; i++) {
          //  System.out.print(vectorZ[i] + ",");
        //}
        //System.out.println(" ]\n");
        
        
        
        this.array = new double[this.nRest][this.nVars+1];
        //MTX
        for(int i=0; i<this.matriz.length; i++) {
            for(int j=0; j<this.matriz[0].length; j++) {
                //System.out.print("[ " + matriz[i][j] + " ] ");
                this.array[i][j] = matriz[i][j];
            }
            //System.out.println("");
        }
        
        //D
        //System.out.print("[ ");
        for(int i=0; i<this.vectorD.length; i++) {
            //System.out.print(vectorD[i] + ",");
            this.array[i][this.array.length-1] = vectorD[i];
        }
        //System.out.println(" ]\n");
        
        //igualdades
        this.desigualdades = new String[this.combo.length];
        for(int i=0; i<this.combo.length; i++) {
            //System.out.println("i: " + i + " " + this.combo[i].getSelectedItem().toString());
            desigualdades[i] = this.combo[i].getSelectedItem().toString();
        }
        

        if(this.jComboBoxObjetivo.getSelectedItem().toString().equals("Maximizar")) {
            this.maximizar = true;
        } else {
            this.maximizar = false;
        }
        
        this.guiLoader.setNrest(this.nRest);
        this.guiLoader.setNvars(this.nVars);
        this.guiLoader.setIsMax(this.maximizar);
        this.guiLoader.setArray(this.array);
        this.guiLoader.setIgualdades(this.desigualdades);
        this.guiLoader.setZ(this.vectorZ);
        
        this.guiLoader.leerDeGUI();
        
        this.simplexModel = new SimplexTable();
        this.simplexModel.simplexFromGUI(guiLoader);
    }
    
    private void crearTablaSimplex(int maximizar) {
        // O min 1 Max
        float[] rest = new float[this.nRest];
        int ii=0;
        this.tablaSimplex = new String[this.nRest+1][(this.nVars+this.nRest+1)];
        for(int i=0; i<tablaSimplex.length; i++) {
            for(int j=0; j<tablaSimplex[0].length; j++) {
                this.tablaSimplex[i][j] = "0";
            }
        }
        if(maximizar == 0) {
            for(int i=0; i<this.vectorZ.length; i++) {
                vectorZ[i] = vectorZ[i] * -1;
            }
            
            for(int i=0; i<this.combo.length; i++) {
                if(this.combo[i].getSelectedItem().toString().equals(">=")) {
                    rest[ii++] = -1;
                } else {
                    rest[ii++] = 1;
                }
            }
        } else {
            for(int i=0; i<this.combo.length; i++) {
                if(this.combo[i].getSelectedItem().toString().equals(">=")) {
                    rest[ii++] = -1;
                } else {
                    rest[ii++] = 1;
                }
            }
        }
    }
    
    private void llena(int vars, int rest) {
        
        this.nVars = vars;
        this.nRest = rest;
        this.jPanel3.removeAll();
        
        int x=20;
        int y=90;
        int c = vars;
        int nvars = vars;
        int hasta;
        int cv = 1;
        
        
        
        
        
        //20
        JLabel j = new JLabel("Función Z");
        j.setBounds(20, 30, 150, 30);
        this.jPanel3.add(j);
        this.z = new JTextField[vars];
        for(int i=0; i<vars; i++) {
            if(cv>vars)
                cv = 1;
            z[i] = new JTextField();
            z[i].setBounds((20+(i*150)), 60, 100, 30);
            this.jPanel3.add(z[i]);
            j = new JLabel("X"+cv);
            j.setBounds((20+(i*150))+105, 60, 30, 30);
            this.jPanel3.add(j);
            cv++;
        }
        
        vars = vars+1;
        c=vars;
        hasta = vars*rest;
        cv = 1;
        int ci=0;
        this.combo = new JComboBox[rest];
        this.f = new JTextField[hasta];
        for(int i=0; i<hasta; i++) {
            if(cv>vars)
                cv = 1;
            
            if(c==0) {
                
            }
            else if(c==vars-1) {
                if(ci<rest) {
                    combo[ci] = new JComboBox();
                    combo[ci].addItem("<="); combo[ci].addItem(">="); combo[ci].addItem("=");
                    combo[ci].setBounds(x+125, y, 50, 30);
                    this.jPanel3.add(combo[ci++]);
                    x += 180;
                }
                
            }
            else if(c<vars) {
                x += 130;
            } else {
                x=20;
                y+=30;
                c=0;
            }
            
            f[i] = new JTextField();
            f[i].setBounds(x, y, 100, 30);
            this.jPanel3.add(f[i]);
            if(c==vars-1) {
                j = new JLabel("");
            } else if(c<vars-2) {
                j = new JLabel("X"+cv+" + ");
            } else {
                j = new JLabel("X"+cv);
            }
            j.setBounds(x+105, y, 30, 30);
            this.jPanel3.add(j);
            
            cv++; c++;
            
        }
        this.jPanel3.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonResolver;
    private javax.swing.JButton jButtonTBDesdeArchivo;
    private javax.swing.JButton jButtonTBResolver;
    private javax.swing.JComboBox<String> jComboBoxObjetivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemCargaDesdeArchivo;
    private javax.swing.JMenuItem jMenuItemResolver;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextFieldNRest;
    private javax.swing.JTextField jTextFieldNVars;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
